import { VivaDiscipline } from './viva-types';

const QUESTION_BANK: Record<VivaDiscipline, string[]> = {
  phd_thesis_defense: [
    'What is the original contribution of your thesis to the field?',
    'Why did you choose this methodology over alternatives?',
    'What was the most surprising finding in your research?',
    'What are the limits of your claims?',
    'How does your work engage with the critics of your theoretical framework?',
    'What would disprove your central argument?',
    'How would you generalize your findings to other contexts?',
    'What ethical considerations shaped your research design?',
    'How do you respond to the strongest objection to your thesis?',
    'If you could redo the study, what would you change?',
    'How does chapter three follow logically from chapter two?',
    'Define the key term you use most frequently.',
    'What is the scope of your literature review and why did you draw the boundary there?',
    'Who are the key scholars you are in dialogue with?',
    'What are the practical implications of your findings?',
  ],
  medical_viva: [
    'Give me your differential diagnosis for this presentation.',
    'What are the red flag symptoms that would change your management immediately?',
    'How would you modify your management plan for a pregnant patient?',
    'What drug interactions concern you in this case?',
    'How do you handle a patient who refuses treatment you believe is necessary?',
    'Walk me through the complications you would monitor for.',
    'What investigations would you order and why in this order?',
    'A patient deteriorates unexpectedly — what is your systematic approach?',
    'What does the evidence base say about this intervention?',
    'How do you communicate a serious diagnosis to a patient?',
    'What are the ethical considerations in this case?',
    'When would you escalate and to whom?',
    'How does this condition present differently in the elderly?',
    'What is the mechanism of action and why does it matter clinically?',
    'Describe the relevant anatomy for this procedure.',
  ],
  law_oral_exam: [
    'What is the ratio decidendi of the leading case?',
    'How would you distinguish this case from the precedent?',
    'Argue the opposing side — how would they respond to your analysis?',
    'What is the literal versus purposive interpretation debate here?',
    'How does the Human Rights Act bear on this question?',
    'Where does the burden of proof lie and why?',
    'What statutory provisions govern this area and how do they interact?',
    'Give me the strongest objection to your preferred analysis.',
    'How would a court of equity approach this differently?',
    'What policy considerations underpin the rule you are applying?',
    'How has academic commentary shaped the development of this area?',
    'What is the effect of a finding that the contract is void versus voidable?',
    'Walk me through the elements of the cause of action.',
    'How do recent developments in the case law affect your analysis?',
    'If the facts were slightly different in this way, how would the outcome change?',
  ],
  engineering_defense: [
    'What are the key design trade-offs you made and why?',
    'How did you validate your design against real-world constraints?',
    'What are the failure modes of your system and how did you mitigate them?',
    'How does your solution scale to 10× the current load?',
    'Where did you sacrifice performance for cost, or cost for performance?',
    'What are the boundary conditions of your model?',
    'How would you detect and respond to a fault in production?',
    'What testing methodology did you use and what did you not test?',
    'What is the environmental impact of your design choices?',
    'How does your approach compare to the industry standard?',
    'What assumptions underlie your mathematical model?',
    'Describe the iterative refinement process for a critical component.',
    'What would you do differently given another six months?',
    'How did you handle the uncertainty in your input data?',
    'What safety standards apply and how did you meet them?',
  ],
  mba_capstone: [
    'How did you size the total addressable market?',
    'Walk me through your unit economics — what drives the contribution margin?',
    'What is your sustainable competitive advantage and how defensible is it?',
    'What is the CAC payback period and how does it compare to the industry?',
    'Run me through the downside scenario — what breaks first?',
    'What is your exit strategy and what multiple is realistic?',
    'How much capital do you need and what does it buy you exactly?',
    'Who is the most dangerous competitor and why haven\'t they done this already?',
    'What assumption in your model is most likely to be wrong?',
    'How would you prioritise your first 90 days of execution?',
    'What does the customer acquisition funnel look like in detail?',
    'How sensitive is your IRR to changes in the churn rate?',
    'What is the regulatory risk and how are you managing it?',
    'Why is now the right time for this business?',
    'What does your go-to-market strategy assume about customer behaviour?',
  ],
  professional_board: [
    'You discover a serious error made by a colleague — what do you do?',
    'How do you handle a conflict of interest in your current role?',
    'A client pressures you to act unethically — walk me through your response.',
    'How do you communicate a complex finding to a non-specialist stakeholder?',
    'Describe a situation where you had to make a difficult decision under time pressure.',
    'What are your obligations when you suspect a regulatory breach?',
    'How do you stay current with changes in the regulatory framework?',
    'Describe the limits of your professional competence and how you manage them.',
    'What does whistleblowing mean in your professional context and when is it required?',
    'How do you balance client confidentiality against public interest obligations?',
    'Walk me through how you would manage a project that is going off-track.',
    'What is the most ethically complex situation you have faced?',
    'How do you document your decision-making process for accountability?',
    'What continuing professional development have you done recently?',
    'How do you maintain professional independence when under pressure from management?',
  ],
  custom: [
    'What is the central claim of your work?',
    'What is the strongest objection to your position?',
    'What evidence would change your mind?',
    'What are the limits of your approach?',
    'What assumptions are you making that you have not made explicit?',
    'How does your work relate to what others have done?',
    'What are the practical implications of your conclusions?',
    'Define the most important term in your argument.',
    'Where is your reasoning most vulnerable?',
    'What would you do differently with more time or resources?',
    'How do you know what you claim to know?',
    'Who is your intended audience and what do they need from this work?',
    'What is the significance of this for the broader field?',
    'Summarize your core argument in three sentences.',
    'What comes next — what does your work open up?',
  ],
};

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function getVivaSeedQuestions(discipline: VivaDiscipline, n = 5): string[] {
  return shuffle(QUESTION_BANK[discipline] ?? QUESTION_BANK.custom).slice(0, n);
}
